/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'diego' at '6/8/17 7:14 PM' with Gradle 2.10
 *
 * @author diego, @date 6/8/17 7:14 PM
 */
public class Person {
    public boolean someLibraryMethod() {
        return true;
    }
}
